server.port=8080
spring.application.name=TresorBackend
CROSS_ORIGIN=http://localhost:3000

# ---------------------------------------------------------
# MARIADB CONNECTION
# ---------------------------------------------------------
spring.datasource.url=jdbc:mariadb://localhost:3306/tresor_db
spring.datasource.username=root

# WICHTIG: Hier muss das Passwort rein, mit dem du dich eben
# in phpMyAdmin eingeloggt hast!
spring.datasource.password=1234

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---------------------------------------------------------
# SECURITY
# ---------------------------------------------------------
app.jwt.secret=dfniudsIDFsdfgsdfg2UNBfdsifze23948assob!
google.recaptcha.secret=6Ld-2BYsAAAAAPIoSK09yjnhHTsPMYBPCXWQpIwk

# ---------------------------------------------------------
# FIREBASE
# ---------------------------------------------------------
app.firebase.config-path=firebase-key.json